# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:        Noah Hamann
tagline:      "Noah Hamann ~ Ideas and images jotted down so I don't forget them."
description:  "Ideas and images jotted down so I don't forget them."
url:              http://hyde.getpoole.com

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/poole/hyde
